name: Build

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - name: Prep
      run: sudo apt-get install libasound-dev -y
      
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/mouse_mover mouse_mover
        chmod 777 mouse_mover
        tar cpfz mouse_mover.tar.gz mouse_mover
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: mouse_mover.tar.gz

  win_build:
    runs-on: windows-latest
    steps:
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/mouse_mover mouse_mover
        7z a mouse_mover.zip mouse_mover.exe
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: mouse_mover.zip
