name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - name: Prep
      run: sudo apt-get install libasound-dev libxdo-dev -y

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.72.0
      
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/mouse_mover mouse_mover
        chmod 777 mouse_mover
        tar cpfz mouse_mover_linux_x86_64.tar.gz mouse_mover
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: mouse_mover_linux_x86_64.tar.gz

  macos_build:
    runs-on: macos-latest

    steps:
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        default: true
        override: true

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/mouse_mover mouse_mover
        chmod 777 mouse_mover
        tar cpfz mouse_mover_darwin_x86_64.tar.gz mouse_mover
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: mouse_mover_darwin_x86_64.tar.gz

  win_build:
    runs-on: windows-latest
    steps:
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/mouse_mover mouse_mover
        7z a mouse_mover_windows_x86_64.zip mouse_mover.exe
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: mouse_mover_windows_x86_64.zip
